version: '3.8'
services:
  jupyter:
    platform: linux/amd64
    build: .
    volumes:
      - .:/usr/src/app
      - ~/.vscode_server:/root/.vscode-server
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes

volumes:
  db_data: